name: med-scanner

services:
  backend:
    container_name: backend
    build: ./backend
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - FRONTEND_URL=http://frontend:8001
      - ML_APP_URL=http://ml:8004
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8001:8001"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
      - NEXT_PUBLIC_VIEWER_URL=http://viewer:8002

  viewer:
    container_name: viewer
    build: ./viewer
    ports:
      - "8002:8002"
      - "8003:8003"

  ml:
    container_name: ml
    build: ./ml
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - "8004:8004"

  database:
    container_name: database
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=MedScannerDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
