window.config = {
  routerBasename: "/",
  whiteLabeling: {
    createLogoComponentFn: (e) => e.createElement("div", {}, ""),
  },
  extensions: [],
  modes: [],
  customizationService: {},
  showStudyList: false,
  maxNumberOfWebWorkers: 3,
  showWarningMessageForCrossOrigin: false,
  showCPUFallbackMessage: !0,
  showLoadingIndicator: !0,
  experimentalStudyBrowserSort: !1,
  strictZSpacingForVolumeViewport: !0,
  groupEnabledModesFirst: !0,
  maxNumRequests: { interaction: 100, thumbnail: 75, prefetch: 25 },
  defaultDataSourceName: "medscanner-dicomweb",
  dataSources: [
    {
      namespace: "@ohif/extension-default.dataSourcesModule.dicomweb",
      sourceName: "medscanner-dicomweb",
      configuration: {
        friendlyName: "MedScanner Server",
        name: "medscanner",
        qidoSupportsIncludeField: true,
        imageRendering: "wadors",
        thumbnailRendering: "wadors",
        enableStudyLazyLoad: true,
        supportsFuzzyMatching: true,
        supportsWildcard: !0,
        staticWado: false,
        singlepart: "bulkdata,video",
        bulkDataURI: { enabled: !0, relativeResolution: "studies" },
        onConfiguration: (e, o) => {
          const a = o.query.get("dicomUrl");
          console.log("dicomUrl", a);
          const proxyUrl = "https://viewer-proxy.medscanner.health"; // TODO: expose this as an environment variable

          return (
            a
              ? {
                  ...e,
                  wadoRoot: `${proxyUrl}/${a}`,
                  qidoRoot: `${proxyUrl}/${a}`,
                  wadoUriRoot: `${proxyUrl}/${a}`,
                }
              : e
          );
        },
      },
    },
    {
      namespace: "@ohif/extension-default.dataSourcesModule.dicomweb",
      sourceName: "dicomweb",
      configuration: {
        friendlyName: "AWS S3 Static wado server",
        name: "aws",
        wadoUriRoot: "https://d33do7qe4w26qo.cloudfront.net/dicomweb",
        qidoRoot: "https://d33do7qe4w26qo.cloudfront.net/dicomweb",
        wadoRoot: "https://d33do7qe4w26qo.cloudfront.net/dicomweb",
        qidoSupportsIncludeField: !1,
        imageRendering: "wadors",
        thumbnailRendering: "wadors",
        enableStudyLazyLoad: !0,
        supportsFuzzyMatching: !1,
        supportsWildcard: !0,
        staticWado: !0,
        singlepart: "bulkdata,video",
        bulkDataURI: { enabled: !0, relativeResolution: "studies" },
        omitQuotationForMultipartRequest: !0,
      },
    },
    {
      namespace: "@ohif/extension-default.dataSourcesModule.dicomweb",
      sourceName: "ohif2",
      configuration: {
        friendlyName: "AWS S3 Static wado secondary server",
        name: "aws",
        wadoUriRoot: "https://d28o5kq0jsoob5.cloudfront.net/dicomweb",
        qidoRoot: "https://d28o5kq0jsoob5.cloudfront.net/dicomweb",
        wadoRoot: "https://d28o5kq0jsoob5.cloudfront.net/dicomweb",
        qidoSupportsIncludeField: !1,
        supportsReject: !1,
        imageRendering: "wadors",
        thumbnailRendering: "wadors",
        enableStudyLazyLoad: !0,
        supportsFuzzyMatching: !1,
        supportsWildcard: !0,
        staticWado: !0,
        singlepart: "bulkdata,video",
        bulkDataURI: { enabled: !0, relativeResolution: "studies" },
        omitQuotationForMultipartRequest: !0,
      },
    },
    {
      namespace: "@ohif/extension-default.dataSourcesModule.dicomweb",
      sourceName: "ohif3",
      configuration: {
        friendlyName: "AWS S3 Static wado secondary server",
        name: "aws",
        wadoUriRoot: "https://d3t6nz73ql33tx.cloudfront.net/dicomweb",
        qidoRoot: "https://d3t6nz73ql33tx.cloudfront.net/dicomweb",
        wadoRoot: "https://d3t6nz73ql33tx.cloudfront.net/dicomweb",
        qidoSupportsIncludeField: !1,
        supportsReject: !1,
        imageRendering: "wadors",
        thumbnailRendering: "wadors",
        enableStudyLazyLoad: !0,
        supportsFuzzyMatching: !1,
        supportsWildcard: !0,
        staticWado: !0,
        singlepart: "bulkdata,video",
        bulkDataURI: { enabled: !0, relativeResolution: "studies" },
        omitQuotationForMultipartRequest: !0,
      },
    },
    {
      namespace: "@ohif/extension-default.dataSourcesModule.dicomweb",
      sourceName: "local5000",
      configuration: {
        friendlyName: "Static WADO Local Data",
        name: "DCM4CHEE",
        qidoRoot: "http://localhost:5000/dicomweb",
        wadoRoot: "http://localhost:5000/dicomweb",
        qidoSupportsIncludeField: !1,
        supportsReject: !0,
        supportsStow: !0,
        imageRendering: "wadors",
        thumbnailRendering: "wadors",
        enableStudyLazyLoad: !0,
        supportsFuzzyMatching: !1,
        supportsWildcard: !0,
        staticWado: !0,
        singlepart: "video",
        bulkDataURI: { enabled: !0, relativeResolution: "studies" },
      },
    },
    {
      namespace: "@ohif/extension-default.dataSourcesModule.dicomwebproxy",
      sourceName: "dicomwebproxy",
      configuration: {
        friendlyName: "dicomweb delegating proxy",
        name: "dicomwebproxy",
      },
    },
    {
      namespace: "@ohif/extension-default.dataSourcesModule.dicomjson",
      sourceName: "dicomjson",
      configuration: { friendlyName: "dicom json", name: "json" },
    },
    {
      namespace: "@ohif/extension-default.dataSourcesModule.dicomlocal",
      sourceName: "dicomlocal",
      configuration: { friendlyName: "dicom local" },
    },
  ],
  httpErrorHandler: (e) => {
    console.warn(e.status), console.warn("test, navigate to https://ohif.org/");
  },
  hotkeys: [
    {
      commandName: "incrementActiveViewport",
      label: "Next Viewport",
      keys: ["right"],
    },
    {
      commandName: "decrementActiveViewport",
      label: "Previous Viewport",
      keys: ["left"],
    },
    { commandName: "rotateViewportCW", label: "Rotate Right", keys: ["r"] },
    { commandName: "rotateViewportCCW", label: "Rotate Left", keys: ["l"] },
    { commandName: "invertViewport", label: "Invert", keys: ["i"] },
    {
      commandName: "flipViewportHorizontal",
      label: "Flip Horizontally",
      keys: ["h"],
    },
    {
      commandName: "flipViewportVertical",
      label: "Flip Vertically",
      keys: ["v"],
    },
    { commandName: "scaleUpViewport", label: "Zoom In", keys: ["+"] },
    { commandName: "scaleDownViewport", label: "Zoom Out", keys: ["-"] },
    { commandName: "fitViewportToWindow", label: "Zoom to Fit", keys: ["="] },
    { commandName: "resetViewport", label: "Reset", keys: ["space"] },
    { commandName: "nextImage", label: "Next Image", keys: ["down"] },
    { commandName: "previousImage", label: "Previous Image", keys: ["up"] },
    {
      commandName: "setToolActive",
      commandOptions: { toolName: "Zoom" },
      label: "Zoom",
      keys: ["z"],
    },
    { commandName: "windowLevelPreset1", label: "W/L Preset 1", keys: ["1"] },
    { commandName: "windowLevelPreset2", label: "W/L Preset 2", keys: ["2"] },
    { commandName: "windowLevelPreset3", label: "W/L Preset 3", keys: ["3"] },
    { commandName: "windowLevelPreset4", label: "W/L Preset 4", keys: ["4"] },
    { commandName: "windowLevelPreset5", label: "W/L Preset 5", keys: ["5"] },
    { commandName: "windowLevelPreset6", label: "W/L Preset 6", keys: ["6"] },
    { commandName: "windowLevelPreset7", label: "W/L Preset 7", keys: ["7"] },
    { commandName: "windowLevelPreset8", label: "W/L Preset 8", keys: ["8"] },
    { commandName: "windowLevelPreset9", label: "W/L Preset 9", keys: ["9"] },
  ],
};
